spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001   # 注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: dev         # dev 默认连接springcloud01数据库
  application:
    name: springcloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 当前数据源类型
    driver-class-name: com.mysql.jdbc.Driver       # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud01?#useUnicode=true&characterEncoding=utf8&useSSL=true&useOldAliasMetadataBehavior=true&allowMultiQueries=true
    username: root
    password: 
    dbcp2: 
      min-idle: 5                   # 数据库连接池的最小连接数
      initial-size: 5               # 初始化连接数
      max-total: 5                  # 最大连接数
      max-wait-millis: 200          # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径
  type-aliases-package: com.myspringcloud.entities  # 所有实体类Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml         # mapper映射文件
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
    
info:
  app.name: springcloud
  company.name: mycompany
  build.artifactId: $project.artifactId$           # 获取项目的artifactId
  build.version: $project.version$                 # 获取项目的版本信息 
---
server:
  port: 8001   # 注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: test       # test默认连接springcloud02数据库
  application:
    name: springcloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 当前数据源类型
    driver-class-name: com.mysql.jdbc.Driver       # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud02?#useUnicode=true&characterEncoding=utf8&useSSL=true&useOldAliasMetadataBehavior=true&allowMultiQueries=true
    username: root
    password: 
    dbcp2: 
      min-idle: 5                   # 数据库连接池的最小连接数
      initial-size: 5               # 初始化连接数
      max-total: 5                  # 最大连接数
      max-wait-millis: 200          # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径
  type-aliases-package: com.myspringcloud.entities  # 所有实体类Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml         # mapper映射文件
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
    
info:
  app.name: springcloud
  company.name: mycompany
  build.artifactId: $project.artifactId$           # 获取项目的artifactId
  build.version: $project.version$                 # 获取项目的版本信息 
   